public class executionClass{

   public static void execute(){
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
     database.executeBatch(new ApexBatchClass ());
   }
}